
server:
  port: 9000


spring:
  application:
    name: auth-service
  datasource:
    password: ${DB_PASSWORD:root}
    username: ${DB_USERNAME:root}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/finalproject}
  jpa:
    show-sql: true
    database-platform: ${DB_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
    #PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update




## MySQL8Dialect