server:
  port: 9000


spring:
  application:
    name: auth-service
  datasource:
    password: ${DB_PASSWORD:123456}
    username: ${DB_USERNAME:postgres}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/library-management-system}
  jpa:
    show-sql: true
    database-platform: ${DB_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
    generate-ddl: true
    hibernate:
      ddl-auto: update



# MySQL8Dialect