server:
  port: 9000
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true




spring:

  application:
    name: auth-service
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/library-management-system}
  jpa:
    show-sql: true
    database-platform: ${DB_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
    generate-ddl: true
    hibernate:
      ddl-auto: update

  # MySQL8Dialect
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
    resources: # Static resources
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
  servlet:
    multipart:
      max-file-size: 10048576