server:
  port: 9000
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true


#logging:
#  level:
#    org.springframework.security:
#      TRACE

spring:
  application:
    name: auth-service
  datasource:
<<<<<<< HEAD
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}

=======
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/library-management-system}
>>>>>>> f1755765bf8b8588a063de01ebc65e9263979fc1

  jpa:
    show-sql: false
    database-platform: ${DB_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
    generate-ddl: true
    hibernate:
      ddl-auto: update

  # MySQL8Dialect
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
    resources: # Static resources
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
  servlet:
    multipart:
      max-file-size: 10048576

